# Generated by Django 4.2.4 on 2023-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_instrumento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
